Update values.yaml to add standardtesting as a baker
tacoinfra/teztnets pull request #17
Opened 2024-03-19 16:57 UTC by michaelkernaghan

adding standard testing as a testnet baker

  standardtesting:
    # tz1aLWKctRdXVvCjF5TSH1u3Co3iuWzfxHvF
    # Standard Testing
    key: edpkvRBvFS5wSvnojdEn9V7nAZyZdPEDqJD4qcVN85j6gBxnD9HhbM
    is_bootstrap_baker_account: true
    bootstrap_balance: "50000000000000000"

2024-03-19 17:19 UTC, drchrispinnock requested changes
can you add your name (or slack ID) please instead of standard testing? we need to be able to get in touch if there is a problem.

2024-03-20 13:01 UTC, michaelkernaghan commented
changed the name to be identifiable as me

2024-03-20 13:03 UTC, michaelkernaghan commented
I have made the new commit thanks, please review

On Tue, Mar 19, 2024 at 10:19 AM Chris Pinnock drchris.tez <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> can you add your name (or slack ID) please instead of standard testing? we
> need to be able to get in touch if there is a problem.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tacoinfra/teztnets/pull/17#pullrequestreview-1946908478>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASWO3VWQCFLZR6HRTMRZ3M3YZBXTBAVCNFSM6AAAAABE56U6HWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBWHEYDQNBXHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-20 19:09 UTC, drchrispinnock approved these changes

2024-03-20 19:09 UTC, merged